### ISSUE TITLE
Create Entity Synthesis Definitions for Entities (DB2 & Oracle) Created through InfraDBPluginJava

### ISSUE THREAD

**Issue by sri-shetty** [newrelic/entity-definitions#249]
Since NR Infra (and OHI) agents doesn't support AIX platform, Customers use FIT InfraDBPluginJava (https://source.datanerd.us/FIT/InfraDBPluginJava) to monitor databases like DB2, Oracle and other DBs. These entities are not visible in the Entity Explorer or Workloads. 

I would like to create Entity Synthesis Definition for DB2 and Oracle database for Manulife.

**Comment by srvaroa** [comment]
Hi @sri-shetty, thanks for raising this one. 

We can help you craft those rules, do you have some samples of telemetry we could look at?

**Comment by sri-shetty** [comment]
[db2 Event Type Keyset](https://insights-embed.newrelic.com/embedded_widget/-2kjrJQk7md41GBvKWA2cW_xgAUFWNXu)
[Oracle Event Type Keyset](https://insights-embed.newrelic.com/embedded_widget/N_FwRI2tAmYF4jkdew0L8T4qY7UG2jyO)
[DB2-QueryName.csv](https://github.com/newrelic-experimental/entity-synthesis-definitions/files/6727804/DB2-QueryName.csv)
[DB2-Unique-QueryName.csv](https://github.com/newrelic-experimental/entity-synthesis-definitions/files/6727805/DB2-Unique-QueryName.csv)
[OracleMetrics.csv](https://github.com/newrelic-experimental/entity-synthesis-definitions/files/6727806/OracleMetrics.csv)

Please ping me sshetty@newrelic.com - if you need additional details.

**Comment by srvaroa** [comment]
Hi @sri-shetty,  registering those types will require a PR adding the relevant configuration files for each type based on that telemetry.  From what I saw in a couple of examples (db2, oracle) this would look pretty similar to other existing types like [ext-ibmmqqueue](https://github.com/newrelic-experimental/entity-synthesis-definitions/blob/master/definitions/ext-ibmmqqueue/definition.yml).

This is a draft example of how the file would look for Oracle.  It should be added at `definitions/ext-oracle/definitions.yml`

Note that I've wild-guessed the values for `name` and `identifier` attributes.   The `identifier` should be a telemetry attribute that is unique within an account. I used `db_unique_name` but you should check whether this attribute is the right one. 

```
domain: EXT
type: ORACLE

synthesis:
  name: database
  identifier: db_unique_name
  conditions:
  - attribute: eventType
    value: Oracle

configuration:
  entityExpirationTime: DAILY
  alertable: true
```

**Comment by naxhh** [comment]
closing since @sri-shetty is already working on this
