### ISSUE TITLE
ext-host metrics are malformed

### ISSUE THREAD

**Issue by rcrocker** [newrelic/entity-definitions#261]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The metrics in ext-host/golden-metrics.yml (e.g., https://github.com/newrelic/entity-definitions/blame/main/definitions/ext-host/golden_metrics.yml#L4) are malformed in a way that is not _wrong_ but is likely misleading.

A metric has a single value; these have multiple values. . This is *likely* not what was intended.

The stream processing system that generates the golden metric data stored in NRDB will only use the first aggregation (in the example, it will construct `newrelic.goldenmetrics.ext.host.systemLoad` using only `sum(datadog.system.load.1)`; the other values are ignored.

If those other values are important, then they should be included as separate metrics.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by naxhh** [comment]
I think this has been resolved and we forgot to close the ticket. I'm seeing current metrics with only 1 value.

Feel free to reopen if i'm missing the point
