### ISSUE TITLE
Adding IO/VM Wait Time Host Golden Metrics

### ISSUE THREAD

**Issue by kolanos** [newrelic/entity-definitions#267]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

I'm not sure how useful golden metrics such as `average(cpuPercent)` are generally, so I'd like to propose some new ones.

* Cpu time spent waiting for I/O (while non-idle): `percentile((cpuIOWaitPercent / cpuPercent) * 100, 50, 75, 95, 99, 99.9)`
* CPU time spent waiting for VM (wile non-idle) `percentile((cpuStealPercent / cpuPercent) * 100, 50, 75, 95, 99, 99.9)`
 
Also, what is the policy about percentiles with golden metrics? I don't see many using percentiles. Is a golden metric of `percentile(cpuPercent, 50, 75, 95, 99, 99.9)` an option?

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Averages for golden metrics aren't terribly useful in my opinion. Would like to see more percentile based golden metrics so I can compare the median to outliers.

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

If a `percentile()` with multiple percentiles specified is discouraged, could do one percentile per golden metric.

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

Can submit a PR, just looking for some guidance on the best approach.

**Comment by naxhh** [comment]
I'm unsure on how percentiles work with the aggregated metrics (golden signals) so I'll ping @rcrocker for that one.
