### ISSUE TITLE
Need NRQL alert condition example

### ISSUE THREAD

**Issue by mtsou-nr** [newrelic/entity-definitions#30]
I am first timer. I need more information or examples on how I can tie NRQL alert condition to a synthesized entity. 
Customer using custom events/attributes in the NRQL alerts.

**Comment by IreneMLC** [comment]
Hi @mtsou-nr, synthesized entities are just like the ones you might be used to dealing with (those defined internally at NewRelic), they all have an `entity.guid` attribute and you could setup a [NRQL alert](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions) against it. Please let me know if this is not what you are looking for.
