### ISSUE TITLE
🐛 Dashboard Sanitization script is improperly changing certain patterns

### ISSUE THREAD

**Issue by thezackm** [newrelic/entity-definitions#469]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Using the dashboard validation script during local development (`npm  --prefix validator run sanitize-dashboards`) is creating broken widgets on a specific query pattern seen in both the existing [kentik_default dashboard](https://github.com/newrelic/entity-definitions/blob/main/definitions/ext-kentik_default/dashboard.json) and the new dashboard being added in PR #468 

## Steps to Reproduce

Clone the repo locally and run the dashboard validation script. No changes should be necessary as the current dashboard for `Kentik Default` entities is in "violation" and should show the problem.

## Expected Behavior

This pattern should be ignored by the validation script since it's a valid dashboard definition and NRQL syntax before being adjusted.

## Relevant Logs / Console output

This is only happening on the following pattern: 

```
"FROM Metric SELECT round(latest(kentik.snmp.hrStorageUsed)*100/latest(kentik.snmp.hrStorageSize), .01) AS 'Used %', round(latest(kentik.snmp.hrStorageSize)*1e-6,.01) AS 'Total (MB)', round(latest(kentik.snmp.hrStorageUsed)*1e-6,.01) AS 'Used (MB)' WHERE provider = 'kentik-poweriq' FACET storage_description LIMIT MAX"
```

Specifically; this portion of the string: 

```
(kentik.snmp.hrStorageSize), .01)
```

Which is being improperly sanitized to this: (replacing `)` with `}` and removing `,`)

```
(kentik.snmp.hrStorageSize} .01)
```

## Additional context

This is negatively impacting each time a PR is run and the sanitization script is executed locally as it puts these dashboards at risk of a breaking change in production with a bad NRQL syntax on these widgets.

![Image 2022-02-28 at 2 04 11 PM](https://user-images.githubusercontent.com/30831476/156051979-2c362b33-a74f-41a3-b7ed-de4a847fcf42.jpg)

![Image 2022-02-28 at 2 05 50 PM](https://user-images.githubusercontent.com/30831476/156052001-25a3603f-8e82-4ce8-bc61-c018b25e1a20.jpg)

**Comment by naxhh** [comment]
We created an internal task to track this ticket EIS-634

**Comment by andre-nr** [comment]
Hi @thezackm,
a fix for this issue has been deployed.
