### ISSUE TITLE
Support AWS Database Migration Service (DMS) as one or more entities

### ISSUE THREAD

**Issue by amoswood** [newrelic/entity-definitions#65]
## Summary

I want to add one or more entity synthesis definitions to support the AWS service of database migration service (DMS) so that we can see DMS instances, DMS tasks, and DMS tables as entities.

## Possible Solution

Create 3 different entities

1. DMS Instance - Track each instance which holds many tasks which run many tables. There are many metrics like CPU and rows per second which are meaningful to track at a higher level than a DMS task.
1. DMS Replication Task - Track each task for replication which has 1 source endpoint and 1 target endpoint for 1 or more tables. Would want to track the name, task stats, logs, etc. here.
2. DMS Table - Track each table and its counts and status.

**Comment by naxhh** [comment]
Hi @amoswood seems we lost this over a few movements. I'll start some conversations about this and see what traction we get on it.

Thanks!

**Comment by naxhh** [comment]
I've been talking with the team in charge of AWS integrations.

DMS is on the backlog of entities to be created but this requires some internal changes to make it happen.
But rest assure we are working to make that happen.
