### ISSUE TITLE
Entity infra-elasticsearchnode Does Not Exist as Entity Type

### ISSUE THREAD

**Issue by kfalconer** [newrelic/entity-definitions#666]
## Description
When navigating to Explorer, ElasticSearch entity type is not defined

## Steps to Reproduce
1. Login to New relic
2. Click Explorer
3. On left navigation menu scroll down to On Host

## Expected Behavior
Expected to see Elasticsearch 
[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

Metrics are currently captured by NR via on host infrastructure agent. 

## Your Environment
* Newrelic Infrastructure Agent 1.27.4
* nri-elasticsearch 4.5.3

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

Definition is defined here: https://github.com/newrelic/entity-definitions/tree/main/definitions/infra-elasticsearchnode

**Comment by naxhh** [comment]
hi @kfalconer ! let me move this internally and see what answer i can get
